# This is a basic workflow to help you get started with Actions
name: Build NCPA Rulebook

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Multi-step process to build the rulebook using pandoc and ghostscript
      - name: Build the Rulebook
        uses: docker://ncpapaintball/rulebook-builder:latest
        with:
          entrypoint: /bin/sh
          args: |
            -c "
            mkdir build/ && \
            pandoc Cover.md -o build/Cover.pdf && \
            pandoc Rulebook.md --toc --toc-depth=6 -o build/Main.pdf && \
            gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=build/rulebook.pdf -dBATCH build/Cover.pdf build/Main.pdf && \
            rm build/Cover.pdf build/Main.pdf \
            "
      - uses: actions/upload-artifact@v1
        with:
          name: Rulebook
          path: build/rulebook.pdf
